In [1]:
import pandas as pd

In [2]:
import numpy as np

In [7]:
df= pd.read_csv("C:/PythonXYZ/DSBDA/expanded_age_income_dataset_pr3.csv")

In [8]:
df

    Person Age Group  Income
0        1     46-55   72130
1        2     18-25   30820
2        3     26-35   46865
3        4     26-35   48748
4        5     46-55   62339
5        6     46-55   79960
6        7     56-65   55607
7        8     18-25   33751
8        9     36-45   63021
9       10     18-25   27677
10      11     26-35   55147
11      12     36-45   67433
12      13     18-25   29422
13      14     18-25   35485
14      15     46-55   78250
15      16     36-45   62196
16      17     26-35   50626
17      18     36-45   56832
18      19     56-65   57505
19      20     18-25   38464
20      21     56-65   51051
21      22     46-55   70336
22      23     26-35   53145
23      24     18-25   29386
24      25     56-65   52168
25      26     26-35   46913
26      27     18-25   39960
27      28     18-25   34292
28      29     56-65   60311
29      30     46-55   66967
30      31     56-65   66358
31      32     46-55   72964
32      33     36-45   70035
33      34     56-65   54681
34      35     26-35   48679
35      36     36-45   59575
36      37     56-65   58081
37      38     46-55   78394
38      39     56-65   67661
39      40     36-45   63609
40      41     46-55   79155
41      42     18-25   32019
42      43     26-35   59121
43      44     26-35   53087
44      45     18-25   30930
45      46     26-35   47186
46      47     18-25   27266
47      48     26-35   56696
48      49     46-55   76171
49      50     26-35   42978

In [9]:
df.describe()

         Person        Income
count  50.00000     50.000000
mean   25.50000  54029.060000
std    14.57738  15278.126939
min     1.00000  27266.000000
25%    13.25000  43949.750000
50%    25.50000  55377.000000
75%    37.75000  65670.750000
max    50.00000  79960.000000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Person     50 non-null     int64
 1   Age Group  50 non-null     object
 2   Income     50 non-null     int64
dtypes: int64(2), object(1)
memory usage: 1.3+ KB

In [11]:
df.groupby('Age Group').describe()

          Person                                                     Income  \
           count       mean        std  min    25%   50%   75%   max  count
Age Group
18-25       12.0  23.333333  15.035312  2.0  12.25  22.0  31.5  47.0   12.0
26-35       12.0  29.166667  17.481592  3.0  15.50  30.5  44.5  50.0   12.0
36-45        7.0  23.428571  12.567911  9.0  14.00  18.0  34.5  40.0    7.0
46-55       10.0  23.900000  16.696307  1.0   8.25  26.0  36.5  49.0   10.0
56-65        9.0  26.888889  10.105004  7.0  21.00  29.0  34.0  39.0    9.0

                                                                            \
                   mean          std      min       25%      50%       75%
Age Group
18-25      32456.000000  4047.782558  27266.0  29413.00  31474.5  34590.25
26-35      50765.916667  4740.454667  42978.0  47117.75  49687.0  53645.50
36-45      63243.000000  4463.219279  56832.0  60885.50  63021.0  65521.00
46-55      73666.600000  5835.753292  62339.0  70784.50  74567.5  78358.00
56-65      58158.111111  5783.613002  51051.0  54681.00  57505.0  60311.00


               max
Age Group
18-25      39960.0
26-35      59121.0
36-45      70035.0
46-55      79960.0
56-65      67661.0

In [12]:
df.groupby('Age Group').describe().sum()

Person  count        50.000000
        mean        126.717460
        std          71.886126
        min          22.000000
        25%          71.000000
        50%         125.500000
        75%         181.000000
        max         225.000000
Income  count        50.000000
        mean     278289.627778
        std       24870.822798
        min      240466.000000
        25%      262881.750000
        50%      276255.000000
        75%      292425.750000
        max      316737.000000
dtype: float64

In [15]:
df['Age Group'].unique()

array(['46-55', '18-25', '26-35', '56-65', '36-45'], dtype=object)

In [18]:
grouped=df.groupby('Age Group')['Income']

In [19]:
summary_statistics = grouped.agg(['mean', 'median', 'min', 'max', 'std']).round(2)

In [20]:
summary_statistics

               mean   median    min    max      std
Age Group
18-25      32456.00  31474.5  27266  39960  4047.78
26-35      50765.92  49687.0  42978  59121  4740.45
36-45      63243.00  63021.0  56832  70035  4463.22
46-55      73666.60  74567.5  62339  79960  5835.75
56-65      58158.11  57505.0  51051  67661  5783.61

In [23]:
income_lists = df.groupby('Age Group')['Income'].apply(list)

In [24]:
income_lists

Age Group
18-25    [30820, 33751, 27677, 29422, 35485, 38464, 293...
26-35    [46865, 48748, 55147, 50626, 53145, 46913, 486...
36-45    [63021, 67433, 62196, 56832, 70035, 59575, 63609]
46-55    [72130, 62339, 79960, 78250, 70336, 66967, 729...
56-65    [55607, 57505, 51051, 52168, 60311, 66358, 546...
Name: Income, dtype: object